import { KitchenProductsType } from "./kitchen";

export const ModakProducts: KitchenProductsType[] = [
  {
    id: 30,
    name: "Oreo Crunch Modak",
    description:
      "A rich milk chocolate Modak loaded with crunchy Oreo pieces. Smooth chocolate and the familiar cookies-and-cream flavour come together in every bite for an indulgent and satisfying treat.",
    productDetails: [
      "Inside: Milk chocolate & Oreo",
      "Taste: Sweet, creamy",
      "Texture: Smooth & crunchy",
      "Best For: Oreo lovers",
      "Storage: Keep refrigerated",
      "Allergens: Wheat, dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Crunch", value: "Oreo Cookie Pieces" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_30_1.png",
      "/images/product_30_2.png",
      "/images/product_30_3.png",
      "/images/product_30_4.png",
    ],
    price: 129,
    oldPrice: 169,
    rating: 4.8,
    sold: 14,
  },
  {
    id: 31,
    name: "Hazelnut Crunch Modak",
    description:
      "A delicious milk chocolate Modak finished with crunchy roasted hazelnuts. Rich chocolate and nutty hazelnut flavour come together for a satisfying sweet and crunchy bite.",
    productDetails: [
      "Inside: Milk chocolate & hazelnut",
      "Taste: Rich, nutty",
      "Texture: Smooth & crunchy",
      "Best For: Hazelnut lovers",
      "Storage: Keep refrigerated",
      "Allergens: Hazelnut, dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Crunch", value: "Roasted Hazelnuts" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_31_1.png",
      "/images/product_31_2.png",
      "/images/product_31_3.png",
      "/images/product_31_4.png",
    ],
    price: 149,
    oldPrice: 199,
    rating: 4.7,
    sold: 11,
  },
  {
    id: 32,
    name: "Peanut Crunch Modak",
    description:
      "A smooth milk chocolate Modak finished with crunchy roasted peanuts. The rich sweetness of chocolate pairs beautifully with the nutty roasted flavour of peanuts for a deliciously crunchy bite.",
    productDetails: [
      "Inside: Milk chocolate & peanut",
      "Taste: Sweet, nutty",
      "Texture: Smooth & crunchy",
      "Best For: Peanut lovers",
      "Storage: Keep refrigerated",
      "Allergens: Peanut, dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Crunch", value: "Roasted Peanuts" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_32_1.png",
      "/images/product_32_2.png",
      "/images/product_32_3.png",
      "/images/product_32_4.png",
    ],
    price: 125,
    oldPrice: 169,
    rating: 4.6,
    sold: 8,
  },
  {
    id: 33,
    name: "Strawberry Cream Modak",
    description:
      "A creamy and fruity chocolate Modak combining smooth chocolate with sweet strawberry flavour. The rich chocolate pairs beautifully with refreshing strawberry notes for a delightful twist.",
    productDetails: [
      "Inside: Chocolate & strawberry",
      "Taste: Sweet, fruity",
      "Texture: Smooth & creamy",
      "Best For: Strawberry lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Flavour", value: "Strawberry Cream" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_33_1.png",
      "/images/product_33_2.png",
      "/images/product_33_3.png",
      "/images/product_33_4.png",
    ],
    price: 139,
    oldPrice: 189,
    rating: 4.9,
    sold: 17,
  },
  {
    id: 34,
    name: "Caramel Crunch Modak",
    description:
      "A rich milk chocolate Modak finished with sweet caramel and a delicious crunchy topping. Smooth chocolate and buttery caramel flavours create a comforting and indulgent treat.",
    productDetails: [
      "Inside: Milk chocolate & caramel",
      "Taste: Sweet, buttery",
      "Texture: Smooth & crunchy",
      "Best For: Caramel lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Flavour", value: "Buttery Caramel" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_34_1.png",
      "/images/product_34_2.png",
      "/images/product_34_3.png",
      "/images/product_34_4.png",
    ],
    price: 145,
    oldPrice: 199,
    rating: 4.7,
    sold: 13,
  },
  {
    id: 35,
    name: "Coffee Modak",
    description:
      "A rich chocolate Modak infused with the bold aroma and flavour of coffee. Smooth milk chocolate meets deep coffee notes to create a perfectly balanced treat for coffee lovers.",
    productDetails: [
      "Inside: Milk chocolate & coffee",
      "Taste: Rich, coffee-forward",
      "Texture: Smooth & creamy",
      "Best For: Coffee lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Flavour", value: "Bold Coffee" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_35_1.png",
      "/images/product_35_2.png",
      "/images/product_35_3.png",
      "/images/product_35_4.png",
    ],
    price: 129,
    oldPrice: 169,
    rating: 4.6,
    sold: 6,
  },
  {
    id: 36,
    name: "Coconut Modak",
    description:
      "A smooth milk chocolate Modak finished with delicate coconut for a deliciously sweet and tropical twist. Rich chocolate and mild coconut flavour create a simple yet satisfying combination.",
    productDetails: [
      "Inside: Milk chocolate & coconut",
      "Taste: Sweet, coconutty",
      "Texture: Smooth & chewy",
      "Best For: Coconut lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Flavour", value: "Sweet Coconut" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_36_1.png",
      "/images/product_36_2.png",
      "/images/product_36_3.png",
      "/images/product_36_4.png",
    ],
    price: 125,
    oldPrice: 169,
    rating: 4.7,
    sold: 9,
  },
  {
    id: 37,
    name: "Choco Chip Modak",
    description:
      "A chocolate lover's favourite made with rich milk chocolate and plenty of chocolate chips. Every bite delivers smooth chocolate flavour with little bursts of extra chocolate crunch.",
    productDetails: [
      "Inside: Milk chocolate & choco chips",
      "Taste: Rich, chocolatey",
      "Texture: Smooth & crunchy",
      "Best For: Choco lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, wheat, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Crunch", value: "Chocolate Chips" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_37_1.png",
      "/images/product_37_2.png",
      "/images/product_37_3.png",
      "/images/product_37_4.png",
    ],
    price: 135,
    oldPrice: 179,
    rating: 4.8,
    sold: 16,
  },
  {
    id: 38,
    name: "Almond Crunch Modak",
    description:
      "A rich milk chocolate Modak topped with crunchy roasted almonds. Smooth chocolate and the delicious nutty flavour of almonds come together for a satisfying sweet and crunchy treat.",
    productDetails: [
      "Inside: Milk chocolate & almond",
      "Taste: Rich, nutty",
      "Texture: Smooth & crunchy",
      "Best For: Almond lovers",
      "Storage: Keep refrigerated",
      "Allergens: Almond, dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Crunch", value: "Roasted Almonds" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_38_1.png",
      "/images/product_38_2.png",
      "/images/product_38_3.png",
      "/images/product_38_4.png",
    ],
    price: 149,
    oldPrice: 199,
    rating: 4.8,
    sold: 12,
  },
  {
    id: 39,
    name: "Rainbow Sprinkle Modak",
    description:
      "A fun and colourful milk chocolate Modak finished with vibrant rainbow sprinkles. Rich chocolate and colourful crunchy sprinkles make every bite playful, sweet and delicious.",
    productDetails: [
      "Inside: Milk chocolate & sprinkles",
      "Taste: Sweet, chocolatey",
      "Texture: Smooth & crunchy",
      "Best For: Kids & sprinkle lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Topping", value: "Rainbow Sprinkles" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_39_1.png",
      "/images/product_39_2.png",
      "/images/product_39_3.png",
      "/images/product_39_4.png",
    ],
    price: 120,
    oldPrice: 159,
    rating: 4.5,
    sold: 5,
  },
  {
    id: 40,
    name: "White Choco Nut Modak",
    description:
      "A creamy white chocolate Modak finished with crunchy nuts. The smooth sweetness of white chocolate pairs beautifully with roasted nuts for a rich and satisfying bite.",
    productDetails: [
      "Inside: White chocolate & nuts",
      "Taste: Sweet, nutty",
      "Texture: Smooth & crunchy",
      "Best For: White chocolate lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, nuts",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "White Chocolate" },
      { label: "Crunch", value: "Roasted Nuts" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_40_1.png",
      "/images/product_40_2.png",
      "/images/product_40_3.png",
      "/images/product_40_4.png",
    ],
    price: 139,
    oldPrice: 189,
    rating: 4.7,
    sold: 7,
  },
  {
    id: 41,
    name: "White Choco Cranberry Modak",
    description:
      "A creamy white chocolate Modak finished with sweet and tangy cranberry pieces. The rich sweetness of white chocolate is beautifully balanced by the fruity tartness of cranberry.",
    productDetails: [
      "Inside: White chocolate & cranberry",
      "Taste: Sweet, tangy",
      "Texture: Smooth & chewy",
      "Best For: Fruit lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "White Chocolate" },
      { label: "Fruit", value: "Dried Cranberries" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_41_1.png",
      "/images/product_41_2.png",
      "/images/product_41_3.png",
      "/images/product_41_4.png",
    ],
    price: 145,
    oldPrice: 199,
    rating: 4.8,
    sold: 10,
  },
  {
    id: 42,
    name: "White Oreo Crunch Modak",
    description:
      "A creamy white chocolate Modak packed with crunchy Oreo pieces. Sweet white chocolate and the classic cookies-and-cream flavour create an irresistible combination in every bite.",
    productDetails: [
      "Inside: White chocolate & Oreo",
      "Taste: Sweet, creamy",
      "Texture: Smooth & crunchy",
      "Best For: Oreo lovers",
      "Storage: Keep refrigerated",
      "Allergens: Wheat, dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "White Chocolate" },
      { label: "Crunch", value: "Oreo Cookie Pieces" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_42_1.png",
      "/images/product_42_2.png",
      "/images/product_42_3.png",
      "/images/product_42_4.png",
    ],
    price: 149,
    oldPrice: 199,
    rating: 4.9,
    sold: 15,
  },
  {
    id: 43,
    name: "Rose Modak Modak",
    description:
      "A delicate chocolate Modak infused with the elegant flavour of rose. Smooth chocolate and subtle floral notes come together for a unique, fragrant and indulgent festive treat.",
    productDetails: [
      "Inside: Chocolate & rose",
      "Taste: Sweet, floral",
      "Texture: Smooth & creamy",
      "Best For: Rose lovers",
      "Storage: Keep refrigerated",
      "Allergens: Dairy, soy",
    ],
    highlights: [
      { label: "Pieces", value: "10 Modaks" },
      { label: "Chocolate", value: "Milk Chocolate" },
      { label: "Flavour", value: "Delicate Rose" },
      { label: "Eggless", value: "Yes" },
    ],
    images: [
      "/images/product_43_1.png",
      "/images/product_43_2.png",
      "/images/product_43_3.png",
      "/images/product_43_4.png",
    ],
    price: 150,
    oldPrice: 209,
    rating: 4.9,
    sold: 18,
  },
] as const;
