import type { Metadata } from "next";
import "./globals.css";
import { dancingScript, dmSans } from "./lib/fonts";
import Footer from "./layout/footer";
import MainLoader from "./components/mainLoader";
import Navbar from "./layout/navbar";
import Script from "next/script";
import Provider from "./provider/provider";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  ),
  title: "Maya's Craft & Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-KT0PF5RDET"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-KT0PF5RDET');
          `}
        </Script>
      </head>
      <body className={`${dmSans.variable} ${dancingScript.variable}`}>
        <Provider>
          <MainLoader>
            <Navbar />
            {children}
            <Footer />
          </MainLoader>
        </Provider>
      </body>
    </html>
  );
}
