import type { Metadata } from "next";
import "./globals.css";
import { dancingScript, dmSans } from "./lib/fonts";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  ),
  title: "Maya's Craft & Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${dancingScript.variable}`}>
        {children}
      </body>
    </html>
  );
}
